-- Agent Runtime storage for Supabase/PostgreSQL.
--
-- This migration is deliberately separate from agent_runtime_history.sql,
-- which remains the SQLite schema used by the local Python runtime.
-- Run this file as one query in the Supabase SQL Editor. It is additive,
-- transactional, and does not modify business or customer-panel tables.

begin;

-- Fail before creating anything when the trusted actor table is unavailable
-- or has a different key type. The current infrastructure defines actor_id as
-- text; using uuid here would make PostgreSQL reject the foreign keys.
do $agent_runtime_preflight$
declare
    actor_id_type text;
begin
    if to_regclass('public.internal_actors') is null then
        raise exception
            'Agent Runtime migration requires public.internal_actors';
    end if;

    select format_type(a.atttypid, a.atttypmod)
      into actor_id_type
      from pg_attribute a
     where a.attrelid = 'public.internal_actors'::regclass
       and a.attname = 'actor_id'
       and a.attnum > 0
       and not a.attisdropped;

    if actor_id_type is distinct from 'text' then
        raise exception
            'Expected public.internal_actors.actor_id to be text, found %',
            coalesce(actor_id_type, '<missing>');
    end if;
end
$agent_runtime_preflight$;

create table if not exists public.internal_agent_conversations (
    conversation_id text primary key,
    human_actor_id text not null,
    ai_actor_id text not null,
    state_json jsonb not null default '{}'::jsonb,
    created_at timestamptz not null,
    last_active_at timestamptz not null,
    expires_at timestamptz not null,
    reset_at timestamptz,
    constraint internal_agent_conversations_state_object
        check (jsonb_typeof(state_json) = 'object'),
    constraint internal_agent_conversations_human_actor_fk
        foreign key (human_actor_id)
        references public.internal_actors(actor_id)
        on delete restrict,
    constraint internal_agent_conversations_ai_actor_fk
        foreign key (ai_actor_id)
        references public.internal_actors(actor_id)
        on delete restrict
);

create index if not exists idx_internal_agent_conversations_owner
    on public.internal_agent_conversations (human_actor_id, last_active_at);

create index if not exists idx_internal_agent_conversations_expiry
    on public.internal_agent_conversations (expires_at);

create table if not exists public.internal_agent_turns (
    turn_id bigint generated by default as identity primary key,
    run_id text not null unique,
    conversation_id text not null,
    user_text text not null,
    assistant_text text,
    evidence_json jsonb not null default '[]'::jsonb,
    created_at timestamptz not null,
    constraint internal_agent_turns_evidence_array
        check (jsonb_typeof(evidence_json) = 'array'),
    constraint internal_agent_turns_conversation_fk
        foreign key (conversation_id)
        references public.internal_agent_conversations(conversation_id)
        on delete restrict
);

create index if not exists idx_internal_agent_turns_history
    on public.internal_agent_turns (conversation_id, turn_id);

create table if not exists public.internal_agent_turn_leases (
    conversation_id text primary key,
    -- Kept as text without a turn FK, matching the crash-recovery lease model.
    run_id text not null,
    expires_at timestamptz not null,
    constraint internal_agent_turn_leases_conversation_fk
        foreign key (conversation_id)
        references public.internal_agent_conversations(conversation_id)
        on delete restrict
);

create index if not exists idx_internal_agent_turn_leases_expiry
    on public.internal_agent_turn_leases (expires_at);

create table if not exists public.internal_agent_terminology (
    term text primary key,
    meaning text not null,
    scope text not null,
    source text not null,
    -- Deliberately not an FK: confirmed terminology must survive history reset.
    source_run_id text not null,
    confirmed_by_actor_id text not null,
    version integer not null,
    updated_at timestamptz not null,
    constraint internal_agent_terminology_scope_check
        check (scope = 'company'),
    constraint internal_agent_terminology_source_check
        check (source = 'confirmed_by_user'),
    constraint internal_agent_terminology_version_check
        check (version > 0),
    constraint internal_agent_terminology_actor_fk
        foreign key (confirmed_by_actor_id)
        references public.internal_actors(actor_id)
        on delete restrict
);

-- PostgreSQL has no SQLite COLLATE NOCASE. This expression index preserves
-- case-insensitive uniqueness without requiring the citext extension.
create unique index if not exists internal_agent_terminology_term_lower_unique
    on public.internal_agent_terminology (lower(term));

create index if not exists idx_internal_agent_terminology_updated
    on public.internal_agent_terminology (updated_at desc);

create table if not exists public.internal_agent_user_style (
    human_actor_id text primary key,
    preferences_json jsonb not null default '{}'::jsonb,
    constraint internal_agent_user_style_preferences_object
        check (jsonb_typeof(preferences_json) = 'object'),
    constraint internal_agent_user_style_human_actor_fk
        foreign key (human_actor_id)
        references public.internal_actors(actor_id)
        on delete restrict
);

-- These are internal backend tables. No authenticated or anonymous client
-- receives direct access, and no customer-facing RLS policy is created.
alter table public.internal_agent_conversations enable row level security;
alter table public.internal_agent_turns enable row level security;
alter table public.internal_agent_turn_leases enable row level security;
alter table public.internal_agent_terminology enable row level security;
alter table public.internal_agent_user_style enable row level security;

revoke all privileges on table public.internal_agent_conversations
    from anon, authenticated;
revoke all privileges on table public.internal_agent_turns
    from anon, authenticated;
revoke all privileges on table public.internal_agent_turn_leases
    from anon, authenticated;
revoke all privileges on table public.internal_agent_terminology
    from anon, authenticated;
revoke all privileges on table public.internal_agent_user_style
    from anon, authenticated;

-- Identity sequences have their own privileges in PostgreSQL. Resolve the
-- generated sequence from the catalog instead of assuming its physical name.
do $agent_runtime_sequence_privileges$
declare
    turn_id_sequence regclass;
begin
    select pg_get_serial_sequence(
               'public.internal_agent_turns', 'turn_id'
           )::regclass
      into turn_id_sequence;

    if turn_id_sequence is not null then
        execute format(
            'revoke all privileges on sequence %s from anon, authenticated',
            turn_id_sequence
        );
    end if;
end
$agent_runtime_sequence_privileges$;

-- CREATE TABLE IF NOT EXISTS must not silently accept an incompatible table
-- left by a partial/manual attempt. Abort the transaction if any critical
-- PostgreSQL type differs from the schema expected by this migration.
do $agent_runtime_postflight$
declare
    mismatch text;
    nullable_mismatch text;
    default_mismatch text;
    missing_constraints text;
begin
    with expected(table_name, column_name, data_type) as (
        values
            ('internal_agent_conversations', 'conversation_id', 'text'),
            ('internal_agent_conversations', 'human_actor_id', 'text'),
            ('internal_agent_conversations', 'ai_actor_id', 'text'),
            ('internal_agent_conversations', 'state_json', 'jsonb'),
            ('internal_agent_conversations', 'created_at', 'timestamp with time zone'),
            ('internal_agent_conversations', 'last_active_at', 'timestamp with time zone'),
            ('internal_agent_conversations', 'expires_at', 'timestamp with time zone'),
            ('internal_agent_conversations', 'reset_at', 'timestamp with time zone'),
            ('internal_agent_turns', 'turn_id', 'bigint'),
            ('internal_agent_turns', 'run_id', 'text'),
            ('internal_agent_turns', 'conversation_id', 'text'),
            ('internal_agent_turns', 'user_text', 'text'),
            ('internal_agent_turns', 'assistant_text', 'text'),
            ('internal_agent_turns', 'evidence_json', 'jsonb'),
            ('internal_agent_turns', 'created_at', 'timestamp with time zone'),
            ('internal_agent_turn_leases', 'conversation_id', 'text'),
            ('internal_agent_turn_leases', 'run_id', 'text'),
            ('internal_agent_turn_leases', 'expires_at', 'timestamp with time zone'),
            ('internal_agent_terminology', 'term', 'text'),
            ('internal_agent_terminology', 'meaning', 'text'),
            ('internal_agent_terminology', 'scope', 'text'),
            ('internal_agent_terminology', 'source', 'text'),
            ('internal_agent_terminology', 'source_run_id', 'text'),
            ('internal_agent_terminology', 'confirmed_by_actor_id', 'text'),
            ('internal_agent_terminology', 'version', 'integer'),
            ('internal_agent_terminology', 'updated_at', 'timestamp with time zone'),
            ('internal_agent_user_style', 'human_actor_id', 'text'),
            ('internal_agent_user_style', 'preferences_json', 'jsonb')
    ), actual as (
        select c.table_name, c.column_name, c.data_type
          from information_schema.columns c
         where c.table_schema = 'public'
           and c.table_name like 'internal_agent_%'
    )
    select string_agg(
               format('%I.%I expected %s, found %s',
                      e.table_name, e.column_name, e.data_type,
                      coalesce(a.data_type, '<missing>')),
               '; ' order by e.table_name, e.column_name)
      into mismatch
      from expected e
      left join actual a using (table_name, column_name)
     where a.data_type is distinct from e.data_type;

    if mismatch is not null then
        raise exception 'Incompatible existing Agent Runtime schema: %', mismatch;
    end if;

    with expected(table_name, column_name) as (
        values
            ('internal_agent_conversations', 'conversation_id'),
            ('internal_agent_conversations', 'human_actor_id'),
            ('internal_agent_conversations', 'ai_actor_id'),
            ('internal_agent_conversations', 'state_json'),
            ('internal_agent_conversations', 'created_at'),
            ('internal_agent_conversations', 'last_active_at'),
            ('internal_agent_conversations', 'expires_at'),
            ('internal_agent_turns', 'turn_id'),
            ('internal_agent_turns', 'run_id'),
            ('internal_agent_turns', 'conversation_id'),
            ('internal_agent_turns', 'user_text'),
            ('internal_agent_turns', 'evidence_json'),
            ('internal_agent_turns', 'created_at'),
            ('internal_agent_turn_leases', 'conversation_id'),
            ('internal_agent_turn_leases', 'run_id'),
            ('internal_agent_turn_leases', 'expires_at'),
            ('internal_agent_terminology', 'term'),
            ('internal_agent_terminology', 'meaning'),
            ('internal_agent_terminology', 'scope'),
            ('internal_agent_terminology', 'source'),
            ('internal_agent_terminology', 'source_run_id'),
            ('internal_agent_terminology', 'confirmed_by_actor_id'),
            ('internal_agent_terminology', 'version'),
            ('internal_agent_terminology', 'updated_at'),
            ('internal_agent_user_style', 'human_actor_id'),
            ('internal_agent_user_style', 'preferences_json')
    )
    select string_agg(
               format('%I.%I', e.table_name, e.column_name),
               '; ' order by e.table_name, e.column_name
           )
      into nullable_mismatch
      from expected e
      left join information_schema.columns c
        on c.table_schema = 'public'
       and c.table_name = e.table_name
       and c.column_name = e.column_name
     where c.is_nullable is distinct from 'NO';

    if nullable_mismatch is not null then
        raise exception
            'Incompatible existing Agent Runtime nullable columns: %',
            nullable_mismatch;
    end if;

    with expected(table_name, column_name, default_expression) as (
        values
            ('internal_agent_conversations', 'state_json', '''{}''::jsonb'),
            ('internal_agent_turns', 'evidence_json', '''[]''::jsonb'),
            ('internal_agent_user_style', 'preferences_json', '''{}''::jsonb')
    )
    select string_agg(
               format('%I.%I expected default %s, found %s',
                      e.table_name, e.column_name, e.default_expression,
                      coalesce(c.column_default, '<missing>')),
               '; ' order by e.table_name, e.column_name
           )
      into default_mismatch
      from expected e
      left join information_schema.columns c
        on c.table_schema = 'public'
       and c.table_name = e.table_name
       and c.column_name = e.column_name
     where c.column_default is distinct from e.default_expression;

    if default_mismatch is not null then
        raise exception
            'Incompatible existing Agent Runtime JSON defaults: %',
            default_mismatch;
    end if;

    if not exists (
        select 1
          from information_schema.columns
         where table_schema = 'public'
           and table_name = 'internal_agent_turns'
           and column_name = 'turn_id'
           and is_identity = 'YES'
           and identity_generation = 'BY DEFAULT'
    ) then
        raise exception
            'public.internal_agent_turns.turn_id exists but is not an identity column';
    end if;

    with expected(table_name, constraint_name, constraint_type) as (
        values
            ('internal_agent_conversations', 'internal_agent_conversations_pkey', 'p'),
            ('internal_agent_conversations', 'internal_agent_conversations_state_object', 'c'),
            ('internal_agent_conversations', 'internal_agent_conversations_human_actor_fk', 'f'),
            ('internal_agent_conversations', 'internal_agent_conversations_ai_actor_fk', 'f'),
            ('internal_agent_turns', 'internal_agent_turns_pkey', 'p'),
            ('internal_agent_turns', 'internal_agent_turns_run_id_key', 'u'),
            ('internal_agent_turns', 'internal_agent_turns_evidence_array', 'c'),
            ('internal_agent_turns', 'internal_agent_turns_conversation_fk', 'f'),
            ('internal_agent_turn_leases', 'internal_agent_turn_leases_pkey', 'p'),
            ('internal_agent_turn_leases', 'internal_agent_turn_leases_conversation_fk', 'f'),
            ('internal_agent_terminology', 'internal_agent_terminology_pkey', 'p'),
            ('internal_agent_terminology', 'internal_agent_terminology_scope_check', 'c'),
            ('internal_agent_terminology', 'internal_agent_terminology_source_check', 'c'),
            ('internal_agent_terminology', 'internal_agent_terminology_version_check', 'c'),
            ('internal_agent_terminology', 'internal_agent_terminology_actor_fk', 'f'),
            ('internal_agent_user_style', 'internal_agent_user_style_pkey', 'p'),
            ('internal_agent_user_style', 'internal_agent_user_style_preferences_object', 'c'),
            ('internal_agent_user_style', 'internal_agent_user_style_human_actor_fk', 'f')
    )
    select string_agg(
               format('%I.%I', e.table_name, e.constraint_name),
               '; ' order by e.table_name, e.constraint_name
           )
      into missing_constraints
      from expected e
     where not exists (
         select 1
           from pg_constraint c
           join pg_class t on t.oid = c.conrelid
           join pg_namespace n on n.oid = t.relnamespace
          where n.nspname = 'public'
            and t.relname = e.table_name
            and c.conname = e.constraint_name
            and c.contype = e.constraint_type::"char"
     );

    if missing_constraints is not null then
        raise exception
            'Incompatible existing Agent Runtime schema; missing constraints: %',
            missing_constraints;
    end if;

    if to_regclass(
        'public.internal_agent_terminology_term_lower_unique'
    ) is null then
        raise exception
            'Missing case-insensitive unique terminology index';
    end if;
end
$agent_runtime_postflight$;

commit;
